[package]
name = "lli"
version = "0.1.0"
authors = ["9tin9tin9 <9tin9tin9@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
ahash = "0.7.4"

[profile.release]
lto = true
panic = "abort"
debug = true
incremental = true

[profile.dev]
debug = true
incremental = true
